name: build

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        target:
          - Windows
          - Linux
        include:
          - target: Windows
            os: windows-latest
            name: Windows
            architecture: AMD64

          - target: Linux
            os: ubuntu-latest
            name: Linux
            architecture: AMD64

    name: Build on ${{ matrix.os }} with ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout SwiftShader
        uses: actions/checkout@v3
        with:
          repository: google/swiftshader
          path: SwiftShader

      - name: Initialize CMake
        working-directory: ${{ github.workspace }}/SwiftShader/build
        run: cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build
        working-directory: ${{ github.workspace }}/SwiftShader/build
        run: cmake --build . --parallel

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ./vk-unittests
