name: build

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout SwiftShader
    uses: actions/checkout@v3
    with:
      repository: google/swiftshader
      path: SwiftShader

    - name: Get CMake
    uses: lukka/get-cmake@latest

    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/SwiftShader/CMakeLists.txt'
        cmakeAppendedArgs: '--parallel'
        buildDirectory: ${{ github.workspace }}/build

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      run: ./vk-unittests


      